Destejiendo el arco iris es un libro de Richard Dawkins publicado en 1998 y en castellano en 2000 por Tusquets Editores, Barcelona (352 páginas).

El título —dice el autor, un biólogo inglés especialista en zoología, académico de la Universidad de Oxford— procede de un poema de Keats, quien creía que Newton había destruido la poesía del arcoíris al reducirlo a los colores prismáticos.

        Según Dawkins, esta creencia es una equivocación, como lo es, a nivel general, acusar a la ciencia de robarle a la vida la calidez que la hace digna de vivirse. Lejos de provocar frialdad y desolación, la ciencia puede proporcionar asombro reverencial mostrando el sentido de lo maravilloso que hay en el mundo. Quienes se definen como amantes del arte, muchas veces sienten antipatía por la ciencia y la razón, mas no hay nada de amenazador en ellas; al contrario, los misterios no pierden su encanto cuando se resuelven, la solución es muchas veces más bella que el enigma e, incluso, cuando se resuelve un misterio, salen a relucir otros, quizás inspiradores de una poesía más elevada.

Con un estilo cautivador, ameno y al alcance de todo lector, Dawkins trae —desde la astronomía y la genética hasta el lenguaje y la realidad virtual— ejemplos variados que muestran que la ciencia también entraña belleza y que el descubrimiento de los mecanismos que rigen los fenómenos naturales, lejos de destruir la poesía, la ensalzan, revelándonos aspectos sorprendentes que de ninguna otra manera podríamos apreciar o imaginar. La obra es también una crítica contra la “mala poesía” de las pseudociencias. Dawkins aventura una teoría (como darwinista que es): en el caso de nuestra especie, la selección natural (la supervivencia de los mejor adaptados) favorece la credulidad ingenua de los niños, penalizando una actitud mental experimental y escéptica a esa edad. El aprendizaje mediante ensayo y error no es algo positivo en la niñez, pues los errores son demasiado costosos, pudiendo acabar hasta con la vida del que ensaya. De modo que la credulidad en los niños (ante todo lo que digan sus padres, profesores, la gente mayor en general) es algo normal y saludable, pero es algo enfermizo, censurable y trae consecuencias catastróficas si persiste en la vida adulta.

Lamentablemente, la disposición mental hacia la credulidad puede continuar en los adultos a partir del deseo de las comodidades y seguridades perdidas de la niñez, y de ésta se aprovechan las pseudociencias como la astrología, la “ciencia de lo paranormal” (precognición, telepatía, espiritismo), los relatos de visitas extraterrestres y la especulación sobre milagros, coincidencias sobrenaturales y otros ejemplos de “poesía científica mala”.

Dawkins, con ironía pero también con rigor científico, se enfrenta a las pseudociencias mostrando lo que son: fraude, ilusión, alucinación, error o embuste.